#!/bin/sh
export PATH=/sbin:/bin
mkdir -p /dev /root /sys /proc /tmp /var/log /run
mount -t sysfs sysfs /sys
mount -t proc proc /proc
mknod -m 622 /dev/console c 5 1
mknod -m 666 /dev/null c 1 3
mknod -m 666 /dev/tty c 5 0
mknod -m 666 /dev/zero c 1 5
mount -t tmpfs -o size=10% tmpfs /tmp
mount -t tmpfs -o size=5% tmpfs /run
mount / -o remount,size=90%
exec /sbin/init
